controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use app\models\Walktrough;
use yii\helpers\ArrayHelper;

class SiteController extends Controller {

    public $defaultAction = 'step_0';

    /**
     * @var Walktrough
     */
    private $walktrough;

    /**
     * @inheritdoc
     */
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function init() {
        Yii::$app->session->open();
        $this->walktrough = Walktrough::my(Yii::$app->session->id);

        return true;
    }

    private function checkStep($step) {
        if ($step != $this->walktrough->current_step) {
            $this->redirect($this->walktrough->getCurrentAction());
        }
    }

    /**
     * Displays start page or current step (if not 0).
     *
     * @return string
     */
    public function actionStep_0() {
        $this->checkStep(0);

        if (Yii::$app->request->isPost) {
            if ($this->walktrough->login) {
                $this->walktrough->completeStep0();
                $this->redirect($this->walktrough->getCurrentAction());
            } else {
                $login = Yii::$app->request->post('login');

                if (!$login) {
                    Yii::$app->session->setFlash('error', 'Please fill the "Login" field.');
                    $this->refresh();
                } else {
                    $this->walktrough->login = $login;
                    $this->walktrough->save();
                }
            }
        }

        return $this->render('step_0', ['walk' => $this->walktrough]);
    }

    public function actionStep_1() {
        $this->checkStep(1);

        if (Yii::$app->request->isPost) {
            $this->walktrough->completeStep1();

            $this->redirect($this->walktrough->getCurrentAction());
        }

        return $this->render('step_1');
    }

    public function actionStep_2() {
        $this->checkStep(2);

        if (Yii::$app->request->isPost) {
            $ansver = Yii::$app->request->post('ansver');
            $this->walktrough->completeStep2($ansver);

            $this->redirect($this->walktrough->getCurrentAction());
        }

        $a = rand(1, 50);
        $b = rand(1, 50);

        Yii::$app->session->set('a', $a);
        Yii::$app->session->set('b', $b);

        return $this->render('step_2', ['a' => $a, 'b' => $b]);
    }

    public function actionStep_3() {
        $this->checkStep(3);

        if (Yii::$app->request->isPost) {
            $langs = Yii::$app->request->post('langs');
            $this->walktrough->completeStep3($langs);

            $this->redirect($this->walktrough->getCurrentAction());
        }

        $langs = [
            'php'       => 'PHP',
            'python'    => 'Python',
            'js'        => 'JavaScript',
            'csharp'    => 'C#',
            'vb'        => 'Visual Basic'
        ];

        return $this->render('step_3', ['langs' => $langs]);
    }

    public function actionStep_4() {
        $this->checkStep(4);

        if (Yii::$app->request->isPost) {
            $day = Yii::$app->request->post('day');
            $this->walktrough->completeStep4($day);

            $this->redirect($this->walktrough->getCurrentAction());
        }

        $allDays = [
            '1' => 'Monday',
            '2' => 'Tuesday',
            '3' => 'Wednesday',
            '4' => 'Thursday',
            '5' => 'Friday',
            '6' => 'Saturday',
            '7' => 'Sunday'
        ];
        $currDay = date('N');
        $days = [
            $currDay => $allDays[$currDay]
        ];

        while (count($days) < 4) {
            $d = rand(1, 7);
            if (!isset($days[$d])) {
                $days[$d] = $allDays[$d];
            }
        }
        $days = $this->shuffle_assoc($days);

        return $this->render('step_4', ['days' => $days]);
    }

    public function actionStep_5() {
        $this->checkStep(5);

        if (Yii::$app->request->isPost) {
            $status = Yii::$app->request->post('status');
            $this->walktrough->completeStep5($status);

            $this->redirect($this->walktrough->getCurrentAction());
        }

        return $this->render('step_5');
    }

    public function actionStep_6() {
        $this->checkStep(6);
        $this->walktrough->completeStep6();

        return $this->render('step_6', ['w' => $this->walktrough]);
    }

    public function actionTerminate() {
        if ($this->walktrough->end_time > 0) {
            Yii::$app->session->regenerateID();
        } else {
            $this->walktrough->delete();
        }

        $this->redirect(Url::toRoute('/'));
    }

    private function shuffle_assoc($list) {
        if (!is_array($list)) return $list;

        $keys = array_keys($list);
        shuffle($keys);
        $random = array();
        foreach ($keys as $key) {
            $random[$key] = $list[$key];
        }

        return $random;
    }
}

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/step_0.php
<?php

use yii\bootstrap\BaseHtml;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;
use yii\base\Widget;
use app\models\Walktrough;

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Hi there!</h1>

        <p class="lead">Now you can start this course. </p>
    </div>

    <div class="container center">
        <?= BaseHtml::beginForm('', 'post', ['class' => 'col-lg-6 col-lg-offset-3']) ?>

		<?php if($walk->login): ?>
			<h4>Previous course walktroughs</h4>

			<?php $dataProvider = new ActiveDataProvider([
                'query' => Walktrough::find()
			         ->where(['>', 'end_time', 0])
			         ->orderBy('end_time', 'DESC')
		             ->limit(10)
			         ->offset(0),
			    'pagination' => [
                    'pageSize' => 10
			     ]
            ]);

			echo GridView::widget([
			    'dataProvider'   => $dataProvider,
			    'columns'    => [
                    'login',
			        'points',
			        [
			            'attribute' => 'Time spent',
			            'value' => function($data) {
			                 $seconds = $data->end_time - $data->start_time;

    	                     $mins = (int)($seconds/60);
    	                     $secs = $seconds%60;

		                     return "$mins:$secs";
			             }
			         ]
                ]
			]);
			?>
		<?php else: ?>
        	<?= BaseHtml::textInput('login', '', ['placeholder' => 'Please type your login', 'required' => 'required', 'class' => 'form-control']) ?>
        <?php endif;?>
        <br>

        <?= BaseHtml::submitButton('Next ->', ['class' => 'btn btn-lg btn-success']) ?>

        <?= BaseHtml::endForm() ?>
    </div>
</div>

views/site/step_1.php
<?php

use yii\bootstrap\BaseHtml;

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Read</h1>

        <p class="lead">Just read the text</p>
    </div>

    <div class="container center">
        <?= BaseHtml::beginForm('', 'post', ['class' => 'col-lg-6 col-lg-offset-3']) ?>

		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eligendi atque illum consequuntur non aspernatur nisi quidem et velit deserunt modi dolorem adipisci quod accusamus? Ab aliquid architecto hic ullam minima!</p>
		<br />

        <?= BaseHtml::submitButton('Next ->', ['class' => 'btn btn-lg btn-success']) ?>

        <?= BaseHtml::endForm() ?>
    </div>
</div>

views/site/step_2.php
<?php

use yii\bootstrap\BaseHtml;

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Math</h1>

        <p class="lead">Calculate this</p>
    </div>

    <div class="container center">
        <?= BaseHtml::beginForm('', 'post', ['class' => 'col-lg-6 col-lg-offset-3']) ?>

		<?= BaseHtml::textInput('', "$a + $b", ['class' => 'form-control text-center', 'disabled' => 'disabled'])?>
		<span class="text-center">=</span>
		<?= BaseHtml::input('number', 'ansver', '', ['class' => 'form-control text-center', 'placeholder' => 'Type ansver here', 'required' => 'required'])?>
		<br />

        <?= BaseHtml::submitButton('Next ->', ['class' => 'btn btn-lg btn-success']) ?>

        <?= BaseHtml::endForm() ?>
    </div>
</div>

views/site/step_3.php
<?php

use yii\bootstrap\Html;

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Check</h1>

        <p class="lead">Check programming languages you know</p>
    </div>

    <div class="container center">
        <?= Html::beginForm('', 'post', ['class' => 'col-lg-6 col-lg-offset-3']) ?>

		<?= Html::checkboxList('langs', [], $langs, ['class' => 'form-group checkbox'])?>
		<br />

        <?= Html::submitButton('Next ->', ['class' => 'btn btn-lg btn-success']) ?>

        <?= Html::endForm() ?>
    </div>
</div>

views/site/step_4.php
<?php

use yii\bootstrap\Html;

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Radio</h1>

        <p class="lead">Check current day of week</p>
    </div>

    <div class="container center">
        <?= Html::beginForm('', 'post', ['class' => 'col-lg-6 col-lg-offset-3']) ?>

		<?= Html::radioList('day', [], $days, ['class' => 'form-group checkbox'])?>
		<br />

        <?= Html::submitButton('Next ->', ['class' => 'btn btn-lg btn-success']) ?>

        <?= Html::endForm() ?>
    </div>
</div>

views/site/step_5.php
<?php
use yii\bootstrap\Html;

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

	<div class="jumbotron">
		<h1>Video</h1>

		<p class="lead">Yo!</p>
	</div>

	<div class="container center">
        <?= Html::beginForm('', 'post')?>

		<div id="player"></div>
		<?= Html::input('hidden', 'status', -1, ['id' => 'input-status'])?>
		<br />

        <?= Html::submitButton('Next ->', ['class' => 'btn btn-lg btn-success'])?>

        <?= Html::endForm()?>
    </div>
</div>

<script>
  var tag = document.createElement('script');

  tag.src = "https://www.youtube.com/iframe_api";
  var firstScriptTag = document.getElementsByTagName('script')[0];
  firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

  var player;
  function onYouTubeIframeAPIReady() {
    player = new YT.Player('player', {
      height: '390',
      width: '640',
      videoId: 'xh_LJIreB40',
      events: {
        'onReady': onPlayerReady,
        'onStateChange': onPlayerStateChange
      }
    });
  }

  function onPlayerStateChange(event) {
	  var input = document.getElementById('input-status');
	  input.value = event.data;
  }

  function onPlayerReady(event) {
    event.target.playVideo();
  }
</script>

views/site/step_6.php
<?php

use yii\bootstrap\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */

$this->title = 'My Yii Application';
?>
<div class="site-index">

    <div class="jumbotron">
        <h1>Congratulations, <?= $w->login?>!</h1>

        <p class="lead">You are finished with <b><?= $w->points?> points</b> during <b><?= ($w->end_time - $w->start_time)?> seconds</b>.</p>
    </div>

    <div class="container center">
		<div class="col-lg-6 col-lg-offset-3">
			<?= Html::a('Go to Start again', Url::toRoute('site/terminate'), ['class' => 'btn btn-lg btn-info'])?>
		</div>
    </div>
</div>